site: A Cara do Pedro
description: Soluções técnicas com propósito
url: https://ghostspzl13.github.io/acaradopedro

media:
  imagens:
    folder: /imagens
    create: true
    accept:
      - .png
      - .jpg
      - .jpeg
      - .gif

collections:
  posts:
    output: true
    folder: _posts
    fields:
      - { name: title, label: Título, type: string }
      - { name: date, label: Data, type: date }
      - { name: image, label: Imagem, type: image }
      - { name: content, label: Conteúdo, type: text }
